#
# Enable Testing with Travis CI
# See https://travis-ci.org/
#

language: perl
perl:
  - "5.26"
#  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"

addons:
  postgresql: "10"



before_install:
  # We dont't need the system PostgreSQL server, start our own
  - sudo service postgresql stop
  # install pgTAP
  - wget http://api.pgxn.org/dist/pgtap/0.98.0/pgtap-0.98.0.zip && unzip pgtap-0.98.0.zip && cd pgtap-0.98.0 && make && sudo make install

